name: Build Sliver for CentOS5.11 (Static 32-bit)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Static Build (linux/386)

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.0'

      - name: Checkout (fake step, we clone real repo below)
        run: echo "Skipping main repo checkout"

      - name: Clone Sliver source
        run: |
          git clone https://github.com/BishopFox/sliver.git sliver
          cd sliver
          git submodule update --init --recursive

      - name: Build Sliver Client and Server (static linux/386)
        run: |
          cd sliver
          mkdir -p build
          export CGO_ENABLED=0
          export GOOS=linux
          export GOARCH=386
          export GO386=387
          go build -trimpath -buildvcs=false -ldflags="-s -w" -o build/sliver-client ./cmd/client
          go build -trimpath -buildvcs=false -ldflags="-s -w" -o build/sliver-server ./cmd/server
          ldd build/sliver-client || echo "Static binary confirmed"
          ldd build/sliver-server || echo "Static binary confirmed"

      - name: Archive Binaries
        run: |
          cd sliver/build
          zip sliver-centos5-static.zip sliver-client sliver-server

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sliver-centos5-binaries
          path: sliver/build/sliver-centos5-static.zip
