name: Build Sliver for CentOS5.11 (Static 32-bit)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make upx protobuf-compiler gcc-multilib

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.2'

      - name: Install Mage
        run: go install github.com/magefile/mage@latest

      - name: Clone Sliver
        run: |
          git clone https://github.com/BishopFox/sliver.git
          cd sliver
          git submodule update --init --recursive

      - name: Build Sliver with Mage
        run: |
          cd sliver
          export CGO_ENABLED=0
          export GOOS=linux
          export GOARCH=386
          export GO386=softfloat
          mage build

          mkdir -p output
          cp ./build/* output/
          upx -9 output/*

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: sliver-386
          path: sliver/output/

