name: Build Sliver (386 static)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        repository: BishopFox/sliver
        ref: main

    - name: Setup Go 1.22
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install mage
      run: go install github.com/magefile/mage@latest

    - name: Generate assets and build
      run: mage build

    - name: Prepare output and compress with UPX
      run: |
        mkdir -p output
        cp build/sliver-client build/sliver-server output/
        upx -9 output/sliver-client output/sliver-server || echo "UPX compress failed, skipping"

    - name: Verify static binary
      run: |
        ldd output/sliver-client || echo "sliver-client is static"
        ldd output/sliver-server || echo "sliver-server is static"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sliver-binaries
        path: output/
