name: Build Sliver for CentOS5.11 (Static 32-bit)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Static Build (linux/386)

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.0'

      - name: Checkout
        run: echo "Using clone below instead"

      - name: Clone Sliver source
        run: |
          git clone https://github.com/BishopFox/sliver.git sliver
          cd sliver
          git submodule update --init --recursive

      - name: Build Sliver with Makefile (static 386)
        run: |
          cd sliver
          export CGO_ENABLED=0
          export GOOS=linux
          export GOARCH=386
          export GO386=387
          make build
          mkdir -p output
          mv sliver-client output/
          mv sliver-server output/
          ldd output/sliver-client || echo "Static binary confirmed"
          ldd output/sliver-server || echo "Static binary confirmed"

      - name: Archive Binaries
        run: |
          cd sliver/output
          zip sliver-centos5-static.zip sliver-client sliver-server

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sliver-centos5-binaries
          path: sliver/output/sliver-centos5-static.zip
