name: Build Sliver for CentOS 5.11 (386 static)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        repository: BishopFox/sliver
        ref: master

    - name: Setup Go 1.22
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Download assets (generate assetsFs)
      run: |
        cd sliver
        go run ./scripts/download_assets.go

    - name: Build sliver (386 static)
      run: |
        cd sliver
        export CGO_ENABLED=0
        export GOOS=linux
        export GOARCH=386
        export GO386=softfloat
        go build -mod=vendor -trimpath -tags "go_sqlite" -ldflags "-s -w" -o build/sliver-client ./client
        go build -mod=vendor -trimpath -tags "go_sqlite,server" -ldflags "-s -w" -o build/sliver-server ./server

    - name: Prepare output and compress with UPX
      run: |
        cd sliver
        mkdir -p output
        cp build/sliver-client build/sliver-server output/
        upx -9 output/sliver-client output/sliver-server || echo "UPX compress failed, skipping"

    - name: Verify static binary
      run: |
        ldd sliver/output/sliver-client || echo "sliver-client is static"
        ldd sliver/output/sliver-server || echo "sliver-server is static"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sliver-binaries
        path: sliver/output/
