name: Build Sliver for CentOS5.11 (Static 32-bit)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.0'

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y make protobuf-compiler upx

      - name: Clone Sliver
        run: |
          git clone https://github.com/BishopFox/sliver.git
          cd sliver
          git submodule update --init --recursive

      - name: Build Sliver (Static 386)
        run: |
          cd sliver
          export CGO_ENABLED=0
          export GOOS=linux
          export GOARCH=386
          export GO386=softfloat
          make

          mkdir -p output
          cp ./build/* output/

          echo "== 检查是否为静态编译 =="
          ldd output/sliver-client || echo "Static binary confirmed"
          ldd output/sliver-server || echo "Static binary confirmed"

      - name: Zip Binaries
        run: |
          cd sliver/output
          zip sliver-centos5-static.zip sliver-client sliver-server

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: sliver-centos5-static
          path: sliver/output/sliver-centos5-static.zip
