name: build-sliver

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential protobuf-compiler upx wget gcc-multilib

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.2'

      - name: Clone Sliver
        run: |
          git clone https://github.com/BishopFox/sliver.git
          cd sliver
          git submodule update --init --recursive

      - name: Download assets
        run: |
          cd sliver
          make download-assets

      - name: Build Sliver Client/Server
        run: |
          cd sliver
          export CGO_ENABLED=0
          export GOOS=linux
          export GOARCH=386
          export GO386=softfloat
          go build -trimpath -mod=vendor -tags "go_sqlite" -ldflags "-s -w" -o build/sliver-client ./client
          go build -trimpath -mod=vendor -tags "go_sqlite,server" -ldflags "-s -w" -o build/sliver-server ./server

      - name: Pack output
        run: |
          cd sliver
          mkdir -p output
          cp build/* output/
          upx -9 output/*

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sliver-linux-386
          path: sliver/output/
