name: Build Sliver for CentOS5.11 (Static 32-bit)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Static Build (linux/386)

    steps:
      - name: Checkout Sliver
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.17'  # 更低版本更兼容旧 libc

      - name: Build Sliver Client and Server (static linux/386)
        run: |
          mkdir -p build
          export CGO_ENABLED=0
          export GOOS=linux
          export GOARCH=386
          export GO386=387
          # 构建客户端
          go build -trimpath -ldflags="-s -w" -o build/sliver-client ./cmd/client
          # 构建服务端
          go build -trimpath -ldflags="-s -w" -o build/sliver-server ./cmd/server
          # 验证是否为静态编译
          ldd build/sliver-client || echo "Static binary confirmed"
          ldd build/sliver-server || echo "Static binary confirmed"

      - name: Archive Binaries
        run: |
          cd build
          zip sliver-centos5-static.zip sliver-client sliver-server

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sliver-centos5-binaries
