name: Release Server for glibc 2.5 (CentOS 5.11)

description: |
  仅编译并发布适配 glibc 2.5 (CentOS 5.11, i386) 的 sliver server 端二进制。

on:
  push:
    branches: [master]

jobs:
  server386-build:
    name: Release Build Server (Linux 386, glibc 2.5+)
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: "^1.21"

      - name: OS Packages
        run: |
          sudo apt-get update --fix-missing && sudo apt-get -y install \
          git build-essential zlib1g zlib1g-dev wget zip unzip

      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Git Fetch Tags
        run: git fetch --prune --unshallow --tags -f

      - name: Clean old build and generated files
        run: |
          make clean
          rm -rf server/assets/fs/linux/386
          rm -f server/assets/fs/*.zip
          rm -f server/assets/assets_linux_386.go

      - name: Download/generate all assets
        run: make .downloaded_assets

      # 如有 traffic-encoders wasm 依赖，取消注释以下步骤
      # - name: Build traffic-encoders wasm
      #   run: |
      #     cd server/assets/traffic-encoders
      #     make

      - name: Build Linux 386 server (glibc 2.5+)
        run: |
          GOOS=linux GOARCH=386 CGO_ENABLED=0 go build -mod=vendor -trimpath -tags go_sqlite,server -ldflags "-s -w" -o sliver-server_linux-386 ./server
          mkdir -p ./server386_artifacts
          cp ./sliver-server_linux-386* ./server386_artifacts/ 2>/dev/null || true

      - name: Server 386 Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: server-linux386
          path: ./server386_artifacts/
