name: Build Linux 386 Server for CentOS 5.11

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux-386-server:
    name: Build Linux 386 (i686, glibc 2.5+) Server
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Clean old build and generated files
        run: |
          make clean
          rm -rf server/assets/fs/linux/386
          rm -f server/assets/fs/*.zip
          rm -f server/assets/assets_linux_386.go

      - name: Download/generate all assets
        run: make .downloaded_assets

      # 如有 traffic-encoders wasm 依赖，取消注释以下步骤
      # - name: Build traffic-encoders wasm
      #   run: |
      #     cd server/assets/traffic-encoders
      #     make

      - name: Build Linux 386 server
        run: |
          GOOS=linux GOARCH=386 CGO_ENABLED=0 go build -mod=vendor -trimpath -tags go_sqlite,server -ldflags "-s -w" -o sliver-server_linux-386 ./server
          mkdir -p ./linux386_server
          cp ./sliver-server_linux-386* ./linux386_server/ 2>/dev/null || true

      - name: Upload server artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux386-server
          path: ./linux386_server/
